version: "3.8"
name: docker_promtech_opros_backend

services:

  postgres:
    image: postgres:15
    container_name: postgres_promtech
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - promtech
    # restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:6.15
    container_name: pgadmin_promtech
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.org
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - promtech

  redis:
    image: redis:7
    container_name: redis_promtech

volumes:
  postgres-data:
  pgadmin:

networks:
  promtech:
    name: promtech
    driver: bridge
