version: "3.8"
name: docker_promtech_opros_backend

services:
  fastapi:
    image: fastapi_promtech
    build:
      context: .
    container_name: fastapi_promtech
    env_file:
      - .env-non-dev
    depends_on:
      postgres:
       condition: service_healthy
      redis:
        condition: service_healthy
    command: ["/app/docker/app.sh"]
    ports:
      - 8000:8000

  postgres:
    image: postgres:15
    container_name: postgres_promtech
    ports:
      - "5433:5432"
    env_file:
      - .env-non-dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
    # restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis_promtech
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5

volumes:
  postgres-data:
