version: "3.8"
name: docker_promtech_opros_backend

services:
  # fastapi:
  #   image: fastapi_promtech
  #   build:
  #     context: .
  #   container_name: fastapi_promtech
  #   env_file:
  #     - .env-non-dev
  #   depends_on:
  #     - postgres
  #     - redis
  #   command: ["/app/docker/app.sh"]
  #   networks:
  #     - promtech
  #   ports:
  #     - 8000:8000

  postgres:
    image: postgres:15
    container_name: postgres_promtech
    ports:
      - "5433:5432"
    env_file:
      - .env-non-dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - promtech
    # restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis_promtech

volumes:
  postgres-data:
  pgadmin:

networks:
  promtech:
    name: promtech
    driver: bridge
