"""created_at_field

Revision ID: 0d94f59b3f33
Revises: e9bd366d5b68
Create Date: 2023-06-01 18:38:28.979478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d94f59b3f33'
down_revision = 'e9bd366d5b68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form', 'created_at')
    # ### end Alembic commands ###
