"""rename response_time to review_time

Revision ID: 6a25fedb58cd
Revises: fd368972f8e1
Create Date: 2023-06-11 16:45:00.205661

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6a25fedb58cd'
down_revision = 'fd368972f8e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('review_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('review', 'response_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('response_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('review', 'review_time')
    # ### end Alembic commands ###
