"""link_field

Revision ID: a08e0129a82b
Revises: 0d94f59b3f33
Create Date: 2023-06-01 18:47:50.416131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a08e0129a82b'
down_revision = '0d94f59b3f33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form', sa.Column('link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form', 'link')
    # ### end Alembic commands ###
