"""organization_color_fields

Revision ID: e9bd366d5b68
Revises: 510d1096d85b
Create Date: 2023-06-01 14:35:01.457636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9bd366d5b68'
down_revision = '510d1096d85b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form', sa.Column('organiztion', sa.String(), nullable=True))
    op.add_column('form', sa.Column('color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form', 'color')
    op.drop_column('form', 'organiztion')
    # ### end Alembic commands ###
